baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "En generation på tillväxt"
theme = 'endLess'

disablePathToLower = true

[frontmatter]
format = "yaml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  dateFormat = "2006-01-02"
  mainSections = ["content"]
  paginate = 12


[params.api]
    uploadKey = "agnes"

[outputs]
  home = ["HTML", "JSON", "RSS"]
  