name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  HUGO_PORT: ${{ vars.HUGO_PORT }}
  HUGO_TIMEZONE: ${{ vars.HUGO_TIMEZONE }}
  UPLOAD_PORT: ${{ vars.UPLOAD_PORT }}
  GITHUB_USERNAME: ${{ vars.USERNAME }}
  REPO_NAME: endlesshugo
  HUGO_IMAGE_NAME: hindfelt/endlesshugo-hugo
  API_IMAGE_NAME: hindfelt/endlesshugo-api

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Hugo image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.HUGO_IMAGE_NAME }}:latest

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:latest
        env:
          UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
